# This is a basic workflow to help you get started with Actions

name: Build Index

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup cache
      - name: Cache
        uses: actions/cache@v3.0.2
        with:
          path: $GITHUB_WORKSPACE/index
          key: index
          restore-keys: index
      
      - name: Install requests
        shell: bash
        run: python3 -m pip install requests
        
      - name: Download index builder
        shell: bash
        run: |
          if [ -d $GITHUB_WORKSPACE/index ]; then
            cd $GITHUB_WORKSPACE/index
          else
            mkdir -p $GITHUB_WORKSPACE/index
            curl https://raw.githubusercontent.com/TES286-ghpages/files.tes286.site/master/.other/index.py > $GITHUB_WORKSPACE/index/index.py
            cd $GITHUB_WORKSPACE/index
          fi
      
      - name: Build index
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/index
          python3 index.py
      
      - name: Deploy index
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/index
          curl https://raw.githubusercontent.com/TES286-ghpages/files.tes286.site/master/.other/postIndex.py > postIndex.py
          python3 postIndex.py ${{ secrets.TOKEN }} $GITHUB_WORKSPACE/index/index.json
      
      - name: Ckeck index
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          curl -s https://raw.githubusercontent.com/TES286-ghpages/files-index.tes286.site/main/index.json | python3 -c "import json, sys, time; print('OK:', json.load(sys.stdin)['last_updated'] >= time.time(), '\n', 'File: ', json.load(sys.stdin)['last_updated'], 'This: ', time.time())"
