# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup cache
      - name: Cache
        uses: actions/cache@v3.0.2
        with:
          path: $GITHUB_WORKSPACE/index
          key: index
          restore-key: index
      
      # Setup python runtime
      - name: Setup python
        uses: actions/setup-python@v3.1.2
        with: 
          python-version: 3.8
          cache: pip
      
      - name: Install requests
        shell: bash
        run: python3 -m pip install requests
        
      - name: Download index builder
        shell: bash
        run: |
          if [-d $GITHUB_WORKSPACE/index ]; then
            mkdir -p $GITHUB_WORKSPACE/index
            cd $GITHUB_WORKSPACE/index
          else
            mkdir -p $GITHUB_WORKSPACE/index
            curl https://raw.githubusercontent.com/TES286-ghpages/files.tes286.site/master/.other/index.py > $GITHUB_WORKSPACE/index/index.py
            cd $GITHUB_WORKSPACE/index
          fi
      
      - name: Build index
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          python3 index.py
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: ignore # replace / ignore / fail; optional (defaults to fail)
