# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup cache
      - name: Cache
        uses: actions/cache@v3.0.2
        with:
          path: $GITHUB_WORKSPACE/index
          key: index
          restore-keys: index
      
      - name: Install requests
        shell: bash
        run: python3 -m pip install requests
        
      - name: Download index builder
        shell: bash
        run: |
          if [-d $GITHUB_WORKSPACE/index ]; then
            mkdir -p $GITHUB_WORKSPACE/index
            cd $GITHUB_WORKSPACE/index
          else
            mkdir -p $GITHUB_WORKSPACE/index
            curl https://raw.githubusercontent.com/TES286-ghpages/files.tes286.site/master/.other/index.py > $GITHUB_WORKSPACE/index/index.py
            cd $GITHUB_WORKSPACE/index
          fi
      
      - name: Build index
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/index
          python3 index.py
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: ignore # replace / ignore / fail; optional (defaults to fail)
      
      - name: Deploy index
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/index
          if [ -d $GITHUB_WORKSPACE/index/build ]; then
            mkdir -p $GITHUB_WORKSPACE/index/builds
          else
            git clone --depth 1 --branch master git@github.com:TES286-ghpages/files-index.tes286.site.git $GITHUB_WORKSPACE/index/build
          fi
          cd $GITHUB_WORKSPACE/index/build
          cp $GITHUB_WORKSPACE/index/index.json ./index.json
          git add index.json
          git commit -m "Update index"
          git push origin master --force
      
      - name: Ckeck index
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          curl -s https://raw.githubusercontent.com/TES286-ghpages/files-index.tes286.site/main/index.json | python3 -c "import json, sys, time; print('OK:', json.load(sys.stdin)['last_updated'] >= int(time.time()))"
